# Generated by Django 6.0.6 on 2026-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium')], default='freemium', max_length=20),
        ),
    ]
