# Generated by Django 6.0.6 on 2026-07-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('fundamentals_of_nursing', 'Fundamentals of Nursing'), ('medical_surgical_nursing', 'Medical-Surgical Nursing'), ('anatomy_and_physiology', 'Anatomy and Physiology'), ('pharmacology', 'Pharmacology'), ('microbiology_and_parasitology', 'Microbiology and Parasitology'), ('community_health_nursing', 'Community Health Nursing'), ('maternal_and_child_health', 'Maternal and Child Health'), ('mental_health_psychiatric_nursing', 'Mental Health/Psychiatric Nursing'), ('nutrition', 'Nutrition'), ('nursing_research', 'Nursing Research'), ('nursing_education_and_administration', 'Nursing Education and Administration'), ('professional_ethics_and_jurisprudence', 'Professional Ethics and Jurisprudence')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['category', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('rationale', models.TextField(blank=True, help_text='Explanation for why the correct answer is right', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='cbt.question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['question'],
            },
        ),
    ]
